### ISSUE TITLE
Modify The timeout

### ISSUE THREAD

**Issue by glowdan** [amphp/redis#32]
As default, the timeout has set to 1000, [Hear](https://github.com/amphp/redis/blob/master/lib/Connection.php#L137 ) , Can I change it on the begining?

**Comment by kelunik** [comment]
I'll add an option.

**Comment by glowdan** [comment]
And does the amp support 'STREAM_CLIENT_PERSISTENT' for persistent connection？

**Comment by bwoebi** [comment]
No idea, I've never tried it. You'll have to try yourself.

**Comment by kelunik** [comment]
I don't think so, but how does this relate to this issue?

**Comment by kelunik** [comment]
You can now pass a timeout in the connection URI: `tcp://localhost:6379?timeout=3000`. Please test it, I'll tag a new version afterwards.

**Comment by glowdan** [comment]
Thank you for your excellence code.
