### ISSUE TITLE
BLPOP command ignores timeout

### ISSUE THREAD

**Issue by HonzaMac** [amphp/redis#41]
[Blpop command](https://redis.io/commands/blpop) does not block connection until there is any element present.

Is there any solution, how to do it in amphp?

**Comment by HonzaMac** [comment]
I actually dont want to wait for 1 second. 
Is it possible to ask periodically each 5 ms?

**Comment by kelunik** [comment]
The blocking list operations only allow timeouts in seconds.  You can use https://redis.io/commands/lpop and poll of course.

**Comment by HonzaMac** [comment]
This is what I'm actually doing, but I expected, that BLPOP with timeout will behave same in amphp/redis like in regular blocking Redis

**Comment by kelunik** [comment]
Without any timeout it just blocks indefinitely, just like Redis does. We don't have any custom logic.

**Comment by kelunik** [comment]
@HonzaMac Could you elaborate on the difference between "regular blocking Redis" and the current behavior? I don't think there's one.
