### ISSUE TITLE
bug on evalSha function

### ISSUE THREAD

**Issue by vicla31** [amphp/redis#46]
Hi,

There is a bug on evalSha function in lib/Redis.php (l. 1754) 
PHP Warning:  array_merge(): Argument #3 is not an array in vendor/amphp/redis/lib/Redis.php on line 1755
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Amp\Redis\Client::send() must be of the type array, null given, called in vendor/amphp/redis/lib/Redis.php on line 1755 and defined in vendor/amphp/redis/lib/Client.php:111

Fix by casting type array on third argument : (array) sizeof((array) $keys)
Thank you

**Comment by kelunik** [comment]
@vicla31 Do you want to provide a pull request?

**Comment by kelunik** [comment]
See #47 for a fix.

**Comment by kelunik** [comment]
Fixed via #48.
