### ISSUE TITLE
getMultiple method doesn't work

### ISSUE THREAD

**Issue by dmitry-pilipenko** [amphp/redis#71]
Hi,

`\Amp\Redis\Redis::getMultiple(string $key, string ...$keys)` the method receives a key and keys as arguments, but only keys without a first key are passed to array_combine. As a result, we get more answers than there is in the keys.

Result:
```
ValueError: array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements
```

**Comment by kelunik** [comment]
Do you want to provide a PR?

**Comment by kelunik** [comment]
Thanks!
