### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by brstgt** [amphp/redis#76]
Hi guys,

Today it added amphp/redis to our project to replace the classic phpredis implementation. I noticed that a couple of commands are missing - e.g. zrangebyscore, zrevrangebyscore and others.

Those commands are quite simple to implement. Would you accept an MR? What are your requirements on tests etc?

Thanks :)

**Comment by trowski** [comment]
Looks like we forgot to close this after merging these commands in #77. Tagged as `v1.1.0`.

**Comment by kelunik** [comment]
@trowski Seems like you didn't actually tag anything?

**Comment by trowski** [comment]
No, it seems I either forgot to push or the push failed. Since I didn't actually tag, should we review and make changes to #78, merge, then tag?

**Comment by brstgt** [comment]
Aaron Piotrowski ***@***.***> schrieb am Sa. 31. Dez. 2022 um
16:07:
