### ISSUE TITLE
`increment()` fails in a transaction

### ISSUE THREAD

**Issue by Bilge** [amphp/redis#93]
```php
$redis->execute('MULTI');
$redis->increment('foo'); // 'QUEUED'
```
>TypeError : Amp\Redis\RedisClient::increment(): Return value must be of type int, string returned

**Comment by kelunik** [comment]
I think #90 is enough for that and there's no need for reporting individual commands failing within transactions?

**Comment by Bilge** [comment]
At the time I did not realise how broken transactions are in Redis. Literally every command just emits "QUEUED" whilst in a transaction.
